name: Keith Smiley
author: Keith Smiley
url: http://smileykeith.com
feed: /atom.xml
pygments: true
excerpt_separator: "readmore"
permalink: /:year/:month/:day/:title/
include: ['.htaccess']
exclude: ['rakefile.rb', 'Gemfile*', 'build.sh', '*.map']
markdown: rdiscount

paginate: 5

